### ISSUE TITLE
filter enhancement

### ISSUE THREAD

**Issue by sbz** [buixor/nxapi#4]
It will be handy to be able to use glob or regex as the value of the filter in order to match similar uri, e.g:

```
--filter 'uri /customers/customer/site'
--filter 'uri /customers/customer/env'
--filter 'uri /customers/customer/project'
```

will be matched by the following:

```
--filter 'uri /customers/customer/*'
```

**Comment by buixor** [comment]
https://github.com/nbs-system/naxsi/commit/3bb33844e444a8e8163c864d7d4bbdfb5c0ba28b

prefixing '?' to a key will make the match be a regexp, ie.

--filter '?uri ^/foobar'
